// Generated by tools/gen_aceax.py -- do not edit by hand.
class jmfsb_optics_ef_optic_mbs_remote_157
{
    model = "mxa_arsenal_jmfsb_mbs_remote_xm157";
    camo = "STD";
};
class jmfsb_optics_ef_optic_mbs_remote_157_coy
{
    model = "mxa_arsenal_jmfsb_mbs_remote_xm157";
    camo = "CBR";
};
class jmfsb_optics_ef_optic_mbs_remote_157_khk
{
    model = "mxa_arsenal_jmfsb_mbs_remote_xm157";
    camo = "KHK";
};
class jmfsb_optics_ef_optic_mbs_remote_157_sand
{
    model = "mxa_arsenal_jmfsb_mbs_remote_xm157";
    camo = "SND";
};
