// Generated by tools/gen_mig.py from MIG's own configs - re-run rather than hand-edit.

class CfgWeapons {
    class ItemInfo; // defined for real in jmfsb_main (see its CfgWeapons.hpp)
    class MIG_FERRO_BISON_MC;
    class MIG_Ferro_FCPC_MG_AOR1;
    class MIG_Ferro_FCPC_MG_CB;
    class MIG_Ferro_FCPC_MG_OCP;
    class MIG_Ferro_FCPC_Rifleman_AOR1;
    class MIG_Ferro_FCPC_Rifleman_CB;
    class MIG_Ferro_FCPC_Rifleman_OCP;
    class MIG_Ferro_FCPC_SL_AOR1;
    class MIG_Ferro_FCPC_SL_CB;
    class MIG_Ferro_FCPC_SL_OCP;
    class MIG_Ferro_FCPC_Slick_AOR1;
    class MIG_Ferro_FCPC_Slick_CB;
    class MIG_Ferro_FCPC_Slick_OCP;
    class MIG_Ferro_FCPC_TL_AOR1;
    class MIG_Ferro_FCPC_TL_CB;
    class MIG_Ferro_FCPC_TL_OCP;
    class MIG_Ferro_FCPC_slick_nb_AOR1;
    class MIG_Ferro_FCPC_slick_nb_CB;
    class MIG_Ferro_FCPC_slick_nb_OCP;
    class MIG_JPC_JTAC_CB;
    class MIG_JPC_JTAC_OCP;
    class MIG_JPC_MG_CB;
    class MIG_JPC_MG_OCP;
    class MIG_JPC_Rifleman_CB;
    class MIG_JPC_Rifleman_OCP;
    class MIG_JPC_SL_CB;
    class MIG_JPC_SL_OCP;
    class MIG_JPC_Slick_CB;
    class MIG_JPC_Slick_OCP;
    class MIG_TYR_Gunfighter_MAB_MC;
    class MIG_TYR_MG_BLK;
    class MIG_TYR_MG_CB;
    class MIG_TYR_MG_OCP;
    class MIG_TYR_MG_OD;
    class MIG_TYR_Rifleman_BLK;
    class MIG_TYR_Rifleman_CB;
    class MIG_TYR_Rifleman_OCP;
    class MIG_TYR_Rifleman_OD;
    class MIG_TYR_Slick_BLK;
    class MIG_TYR_Slick_CB;
    class MIG_TYR_Slick_NB_BLK;
    class MIG_TYR_Slick_NB_CB;
    class MIG_TYR_Slick_NB_OCP;
    class MIG_TYR_Slick_NB_OD;
    class MIG_TYR_Slick_OCP;
    class MIG_TYR_Slick_OD;
    class MIG_TYR_TL_BLK;
    class MIG_TYR_TL_CB;
    class MIG_TYR_TL_OCP;
    class MIG_TYR_TL_OD;

    class GVAR(MIG_FERRO_BISON_MC): MIG_FERRO_BISON_MC {
        author = QAUTHOR;
        scope = 2;
        scopeArsenal = 2;
        displayName = "[JMSB] Ferro Bison (MC)";
    };

    class GVAR(MIG_Ferro_FCPC_TL_CB): MIG_Ferro_FCPC_TL_CB {
        author = QAUTHOR;
        scope = 2;
        scopeArsenal = 2;
        displayName = "[JMSB] Ferro FCPC TL (CB)";
        class ItemInfo: ItemInfo {
            JMFSB_PLATE_CARRIER_STANDARD_PROTECTION
        };
    };

    class GVAR(MIG_Ferro_FCPC_TL_OCP): MIG_Ferro_FCPC_TL_OCP {
        author = QAUTHOR;
        scope = 2;
        scopeArsenal = 2;
        displayName = "[JMSB] Ferro FCPC TL (OCP)";
        class ItemInfo: ItemInfo {
            JMFSB_PLATE_CARRIER_STANDARD_PROTECTION
        };
    };

    class GVAR(MIG_Ferro_FCPC_TL_AOR1): MIG_Ferro_FCPC_TL_AOR1 {
        author = QAUTHOR;
        scope = 2;
        scopeArsenal = 2;
        displayName = "[JMSB] Ferro FCPC TL (AOR1)";
        class ItemInfo: ItemInfo {
            JMFSB_PLATE_CARRIER_STANDARD_PROTECTION
        };
    };

    class GVAR(MIG_Ferro_FCPC_SL_CB): MIG_Ferro_FCPC_SL_CB {
        author = QAUTHOR;
        scope = 2;
        scopeArsenal = 2;
        displayName = "[JMSB] Ferro FCPC SL (CB)";
        class ItemInfo: ItemInfo {
            JMFSB_PLATE_CARRIER_STANDARD_PROTECTION
        };
    };

    class GVAR(MIG_Ferro_FCPC_SL_OCP): MIG_Ferro_FCPC_SL_OCP {
        author = QAUTHOR;
        scope = 2;
        scopeArsenal = 2;
        displayName = "[JMSB] Ferro FCPC SL (OCP)";
        class ItemInfo: ItemInfo {
            JMFSB_PLATE_CARRIER_STANDARD_PROTECTION
        };
    };

    class GVAR(MIG_Ferro_FCPC_SL_AOR1): MIG_Ferro_FCPC_SL_AOR1 {
        author = QAUTHOR;
        scope = 2;
        scopeArsenal = 2;
        displayName = "[JMSB] Ferro FCPC SL (AOR1)";
        class ItemInfo: ItemInfo {
            JMFSB_PLATE_CARRIER_STANDARD_PROTECTION
        };
    };

    class GVAR(MIG_Ferro_FCPC_Slick_CB): MIG_Ferro_FCPC_Slick_CB {
        author = QAUTHOR;
        scope = 2;
        scopeArsenal = 2;
        displayName = "[JMSB] Ferro FCPC Slick (CB)";
        class ItemInfo: ItemInfo {
            JMFSB_PLATE_CARRIER_STANDARD_PROTECTION
        };
    };

    class GVAR(MIG_Ferro_FCPC_Slick_OCP): MIG_Ferro_FCPC_Slick_OCP {
        author = QAUTHOR;
        scope = 2;
        scopeArsenal = 2;
        displayName = "[JMSB] Ferro FCPC Slick (OCP)";
        class ItemInfo: ItemInfo {
            JMFSB_PLATE_CARRIER_STANDARD_PROTECTION
        };
    };

    class GVAR(MIG_Ferro_FCPC_Slick_AOR1): MIG_Ferro_FCPC_Slick_AOR1 {
        author = QAUTHOR;
        scope = 2;
        scopeArsenal = 2;
        displayName = "[JMSB] Ferro FCPC Slick (AOR1)";
        class ItemInfo: ItemInfo {
            JMFSB_PLATE_CARRIER_STANDARD_PROTECTION
        };
    };

    class GVAR(MIG_Ferro_FCPC_slick_nb_CB): MIG_Ferro_FCPC_slick_nb_CB {
        author = QAUTHOR;
        scope = 2;
        scopeArsenal = 2;
        displayName = "[JMSB] Ferro FCPC Slick (No Belt)(CB)";
        class ItemInfo: ItemInfo {
            JMFSB_PLATE_CARRIER_STANDARD_PROTECTION
        };
    };

    class GVAR(MIG_Ferro_FCPC_slick_nb_OCP): MIG_Ferro_FCPC_slick_nb_OCP {
        author = QAUTHOR;
        scope = 2;
        scopeArsenal = 2;
        displayName = "[JMSB] Ferro FCPC Slick (No Belt)(OCP)";
        class ItemInfo: ItemInfo {
            JMFSB_PLATE_CARRIER_STANDARD_PROTECTION
        };
    };

    class GVAR(MIG_Ferro_FCPC_slick_nb_AOR1): MIG_Ferro_FCPC_slick_nb_AOR1 {
        author = QAUTHOR;
        scope = 2;
        scopeArsenal = 2;
        displayName = "[JMSB] Ferro FCPC Slick (No Belt)(AOR1)";
        class ItemInfo: ItemInfo {
            JMFSB_PLATE_CARRIER_STANDARD_PROTECTION
        };
    };

    class GVAR(MIG_Ferro_FCPC_Rifleman_CB): MIG_Ferro_FCPC_Rifleman_CB {
        author = QAUTHOR;
        scope = 2;
        scopeArsenal = 2;
        displayName = "[JMSB] Ferro FCPC Rifleman (CB)";
        class ItemInfo: ItemInfo {
            JMFSB_PLATE_CARRIER_STANDARD_PROTECTION
        };
    };

    class GVAR(MIG_Ferro_FCPC_Rifleman_OCP): MIG_Ferro_FCPC_Rifleman_OCP {
        author = QAUTHOR;
        scope = 2;
        scopeArsenal = 2;
        displayName = "[JMSB] Ferro FCPC Rifleman (OCP)";
        class ItemInfo: ItemInfo {
            JMFSB_PLATE_CARRIER_STANDARD_PROTECTION
        };
    };

    class GVAR(MIG_Ferro_FCPC_Rifleman_AOR1): MIG_Ferro_FCPC_Rifleman_AOR1 {
        author = QAUTHOR;
        scope = 2;
        scopeArsenal = 2;
        displayName = "[JMSB] Ferro FCPC Rifleman (AOR1)";
        class ItemInfo: ItemInfo {
            JMFSB_PLATE_CARRIER_STANDARD_PROTECTION
        };
    };

    class GVAR(MIG_Ferro_FCPC_MG_CB): MIG_Ferro_FCPC_MG_CB {
        author = QAUTHOR;
        scope = 2;
        scopeArsenal = 2;
        displayName = "[JMSB] Ferro FCPC MG (CB)";
        class ItemInfo: ItemInfo {
            JMFSB_PLATE_CARRIER_STANDARD_PROTECTION
        };
    };

    class GVAR(MIG_Ferro_FCPC_MG_OCP): MIG_Ferro_FCPC_MG_OCP {
        author = QAUTHOR;
        scope = 2;
        scopeArsenal = 2;
        displayName = "[JMSB] Ferro FCPC MG (OCP)";
        class ItemInfo: ItemInfo {
            JMFSB_PLATE_CARRIER_STANDARD_PROTECTION
        };
    };

    class GVAR(MIG_Ferro_FCPC_MG_AOR1): MIG_Ferro_FCPC_MG_AOR1 {
        author = QAUTHOR;
        scope = 2;
        scopeArsenal = 2;
        displayName = "[JMSB] Ferro FCPC MG (AOR1)";
        class ItemInfo: ItemInfo {
            JMFSB_PLATE_CARRIER_STANDARD_PROTECTION
        };
    };

    class GVAR(MIG_JPC_Rifleman_CB): MIG_JPC_Rifleman_CB {
        author = QAUTHOR;
        scope = 2;
        scopeArsenal = 2;
        displayName = "[JMSB] JPC Rifleman (CB)";
        class ItemInfo: ItemInfo {
            JMFSB_PLATE_CARRIER_STANDARD_PROTECTION
        };
    };

    class GVAR(MIG_JPC_Rifleman_OCP): MIG_JPC_Rifleman_OCP {
        author = QAUTHOR;
        scope = 2;
        scopeArsenal = 2;
        displayName = "[JMSB] JPC Rifleman (OCP)";
        class ItemInfo: ItemInfo {
            JMFSB_PLATE_CARRIER_STANDARD_PROTECTION
        };
    };

    class GVAR(MIG_JPC_Slick_CB): MIG_JPC_Slick_CB {
        author = QAUTHOR;
        scope = 2;
        scopeArsenal = 2;
        displayName = "[JMSB] JPC Slick (CB)";
        class ItemInfo: ItemInfo {
            JMFSB_PLATE_CARRIER_STANDARD_PROTECTION
        };
    };

    class GVAR(MIG_JPC_Slick_OCP): MIG_JPC_Slick_OCP {
        author = QAUTHOR;
        scope = 2;
        scopeArsenal = 2;
        displayName = "[JMSB] JPC Slick (OCP)";
        class ItemInfo: ItemInfo {
            JMFSB_PLATE_CARRIER_STANDARD_PROTECTION
        };
    };

    class GVAR(MIG_JPC_MG_CB): MIG_JPC_MG_CB {
        author = QAUTHOR;
        scope = 2;
        scopeArsenal = 2;
        displayName = "[JMSB] JPC MG (CB)";
        class ItemInfo: ItemInfo {
            JMFSB_PLATE_CARRIER_STANDARD_PROTECTION
        };
    };

    class GVAR(MIG_JPC_MG_OCP): MIG_JPC_MG_OCP {
        author = QAUTHOR;
        scope = 2;
        scopeArsenal = 2;
        displayName = "[JMSB] JPC MG (OCP)";
        class ItemInfo: ItemInfo {
            JMFSB_PLATE_CARRIER_STANDARD_PROTECTION
        };
    };

    class GVAR(MIG_JPC_SL_CB): MIG_JPC_SL_CB {
        author = QAUTHOR;
        scope = 2;
        scopeArsenal = 2;
        displayName = "[JMSB] JPC SL (CB)";
        class ItemInfo: ItemInfo {
            JMFSB_PLATE_CARRIER_STANDARD_PROTECTION
        };
    };

    class GVAR(MIG_JPC_SL_OCP): MIG_JPC_SL_OCP {
        author = QAUTHOR;
        scope = 2;
        scopeArsenal = 2;
        displayName = "[JMSB] JPC SL (OCP)";
        class ItemInfo: ItemInfo {
            JMFSB_PLATE_CARRIER_STANDARD_PROTECTION
        };
    };

    class GVAR(MIG_JPC_JTAC_CB): MIG_JPC_JTAC_CB {
        author = QAUTHOR;
        scope = 2;
        scopeArsenal = 2;
        displayName = "[JMSB] JPC JTAC (CB)";
        class ItemInfo: ItemInfo {
            JMFSB_PLATE_CARRIER_STANDARD_PROTECTION
        };
    };

    class GVAR(MIG_JPC_JTAC_OCP): MIG_JPC_JTAC_OCP {
        author = QAUTHOR;
        scope = 2;
        scopeArsenal = 2;
        displayName = "[JMSB] JPC JTAC (OCP)";
        class ItemInfo: ItemInfo {
            JMFSB_PLATE_CARRIER_STANDARD_PROTECTION
        };
    };

    class GVAR(MIG_TYR_Gunfighter_MAB_MC): MIG_TYR_Gunfighter_MAB_MC {
        author = QAUTHOR;
        scope = 2;
        scopeArsenal = 2;
        displayName = "[JMSB] TYR Gunfighter MAB (MC)";
    };

    class GVAR(MIG_TYR_Rifleman_CB): MIG_TYR_Rifleman_CB {
        author = QAUTHOR;
        scope = 2;
        scopeArsenal = 2;
        displayName = "[JMSB] TYR Pico Rifleman (CB)";
        class ItemInfo: ItemInfo {
            JMFSB_PLATE_CARRIER_STANDARD_PROTECTION
        };
    };

    class GVAR(MIG_TYR_Rifleman_OCP): MIG_TYR_Rifleman_OCP {
        author = QAUTHOR;
        scope = 2;
        scopeArsenal = 2;
        displayName = "[JMSB] TYR Pico Rifleman (OCP)";
        class ItemInfo: ItemInfo {
            JMFSB_PLATE_CARRIER_STANDARD_PROTECTION
        };
    };

    class GVAR(MIG_TYR_Rifleman_OD): MIG_TYR_Rifleman_OD {
        author = QAUTHOR;
        scope = 2;
        scopeArsenal = 2;
        displayName = "[JMSB] TYR Pico Rifleman (OD)";
        class ItemInfo: ItemInfo {
            JMFSB_PLATE_CARRIER_STANDARD_PROTECTION
        };
    };

    class GVAR(MIG_TYR_Rifleman_BLK): MIG_TYR_Rifleman_BLK {
        author = QAUTHOR;
        scope = 2;
        scopeArsenal = 2;
        displayName = "[JMSB] TYR Pico Rifleman (BLK)";
        class ItemInfo: ItemInfo {
            JMFSB_PLATE_CARRIER_STANDARD_PROTECTION
        };
    };

    class GVAR(MIG_TYR_TL_CB): MIG_TYR_TL_CB {
        author = QAUTHOR;
        scope = 2;
        scopeArsenal = 2;
        displayName = "[JMSB] TYR Pico TL (CB)";
        class ItemInfo: ItemInfo {
            JMFSB_PLATE_CARRIER_STANDARD_PROTECTION
        };
    };

    class GVAR(MIG_TYR_TL_OCP): MIG_TYR_TL_OCP {
        author = QAUTHOR;
        scope = 2;
        scopeArsenal = 2;
        displayName = "[JMSB] TYR Pico TL (OCP)";
        class ItemInfo: ItemInfo {
            JMFSB_PLATE_CARRIER_STANDARD_PROTECTION
        };
    };

    class GVAR(MIG_TYR_TL_OD): MIG_TYR_TL_OD {
        author = QAUTHOR;
        scope = 2;
        scopeArsenal = 2;
        displayName = "[JMSB] TYR Pico TL (OD)";
        class ItemInfo: ItemInfo {
            JMFSB_PLATE_CARRIER_STANDARD_PROTECTION
        };
    };

    class GVAR(MIG_TYR_TL_BLK): MIG_TYR_TL_BLK {
        author = QAUTHOR;
        scope = 2;
        scopeArsenal = 2;
        displayName = "[JMSB] TYR Pico TL (BLK)";
        class ItemInfo: ItemInfo {
            JMFSB_PLATE_CARRIER_STANDARD_PROTECTION
        };
    };

    class GVAR(MIG_TYR_Slick_CB): MIG_TYR_Slick_CB {
        author = QAUTHOR;
        scope = 2;
        scopeArsenal = 2;
        displayName = "[JMSB] TYR Pico Slick (CB)";
        class ItemInfo: ItemInfo {
            JMFSB_PLATE_CARRIER_STANDARD_PROTECTION
        };
    };

    class GVAR(MIG_TYR_Slick_OCP): MIG_TYR_Slick_OCP {
        author = QAUTHOR;
        scope = 2;
        scopeArsenal = 2;
        displayName = "[JMSB] TYR Pico Slick (OCP)";
        class ItemInfo: ItemInfo {
            JMFSB_PLATE_CARRIER_STANDARD_PROTECTION
        };
    };

    class GVAR(MIG_TYR_Slick_OD): MIG_TYR_Slick_OD {
        author = QAUTHOR;
        scope = 2;
        scopeArsenal = 2;
        displayName = "[JMSB] TYR Pico Slick (OD)";
        class ItemInfo: ItemInfo {
            JMFSB_PLATE_CARRIER_STANDARD_PROTECTION
        };
    };

    class GVAR(MIG_TYR_Slick_BLK): MIG_TYR_Slick_BLK {
        author = QAUTHOR;
        scope = 2;
        scopeArsenal = 2;
        displayName = "[JMSB] TYR Pico Slick (BLK)";
        class ItemInfo: ItemInfo {
            JMFSB_PLATE_CARRIER_STANDARD_PROTECTION
        };
    };

    class GVAR(MIG_TYR_Slick_NB_CB): MIG_TYR_Slick_NB_CB {
        author = QAUTHOR;
        scope = 2;
        scopeArsenal = 2;
        displayName = "[JMSB] TYR Pico Slick (No Belt) (CB)";
        class ItemInfo: ItemInfo {
            JMFSB_PLATE_CARRIER_STANDARD_PROTECTION
        };
    };

    class GVAR(MIG_TYR_Slick_NB_OCP): MIG_TYR_Slick_NB_OCP {
        author = QAUTHOR;
        scope = 2;
        scopeArsenal = 2;
        displayName = "[JMSB] TYR Pico Slick (No Belt) (OCP)";
        class ItemInfo: ItemInfo {
            JMFSB_PLATE_CARRIER_STANDARD_PROTECTION
        };
    };

    class GVAR(MIG_TYR_Slick_NB_OD): MIG_TYR_Slick_NB_OD {
        author = QAUTHOR;
        scope = 2;
        scopeArsenal = 2;
        displayName = "[JMSB] TYR Pico Slick (No Belt) (OD)";
        class ItemInfo: ItemInfo {
            JMFSB_PLATE_CARRIER_STANDARD_PROTECTION
        };
    };

    class GVAR(MIG_TYR_Slick_NB_BLK): MIG_TYR_Slick_NB_BLK {
        author = QAUTHOR;
        scope = 2;
        scopeArsenal = 2;
        displayName = "[JMSB] TYR Pico Slick (No Belt) (BLK)";
        class ItemInfo: ItemInfo {
            JMFSB_PLATE_CARRIER_STANDARD_PROTECTION
        };
    };

    class GVAR(MIG_TYR_MG_CB): MIG_TYR_MG_CB {
        author = QAUTHOR;
        scope = 2;
        scopeArsenal = 2;
        displayName = "[JMSB] TYR Pico MG (CB)";
        class ItemInfo: ItemInfo {
            JMFSB_PLATE_CARRIER_STANDARD_PROTECTION
        };
    };

    class GVAR(MIG_TYR_MG_OCP): MIG_TYR_MG_OCP {
        author = QAUTHOR;
        scope = 2;
        scopeArsenal = 2;
        displayName = "[JMSB] TYR Pico MG (OCP)";
        class ItemInfo: ItemInfo {
            JMFSB_PLATE_CARRIER_STANDARD_PROTECTION
        };
    };

    class GVAR(MIG_TYR_MG_OD): MIG_TYR_MG_OD {
        author = QAUTHOR;
        scope = 2;
        scopeArsenal = 2;
        displayName = "[JMSB] TYR Pico MG (OD)";
        class ItemInfo: ItemInfo {
            JMFSB_PLATE_CARRIER_STANDARD_PROTECTION
        };
    };

    class GVAR(MIG_TYR_MG_BLK): MIG_TYR_MG_BLK {
        author = QAUTHOR;
        scope = 2;
        scopeArsenal = 2;
        displayName = "[JMSB] TYR Pico MG (BLK)";
        class ItemInfo: ItemInfo {
            JMFSB_PLATE_CARRIER_STANDARD_PROTECTION
        };
    };
};
